// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blogmanager_nguyenngocvi_22t1020794.Data;

#nullable disable

namespace blogmanager_nguyenngocvi_22t1020794.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260730032224_SeedPosts")]
    partial class SeedPosts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("blogmanager_nguyenngocvi_22t1020794.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("blogmanager_nguyenngocvi_22t1020794.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Ngọc Vi",
                            Content = "Nội dung bài học C# cơ bản: Tìm hiểu về biến, các kiểu dữ liệu nguyên thủy, vòng lặp (for, while) và cấu trúc rẽ nhánh (if-else, switch-case) trong lập trình...",
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "C# cơ bản",
                            ViewCount = 150
                        },
                        new
                        {
                            Id = 2,
                            Author = "Quang Huy",
                            Content = "Kiến trúc Model-View-Controller (MVC) trong ASP.NET Core giúp tách biệt rõ ràng giữa logic xử lý dữ liệu (Model), giao diện hiển thị (View) và bộ điều hướng (Controller)...",
                            IsPublished = false,
                            PublishedAt = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "MVC nhập môn",
                            ViewCount = 320
                        },
                        new
                        {
                            Id = 3,
                            Author = "Ngọc Vi",
                            Content = "Entity Framework Core là một ORM (Object-Relational Mapper) mạnh mẽ của Microsoft, cho phép lập trình viên thao tác trực tiếp với cơ sở dữ liệu thông qua các đối tượng C#...",
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "EF Core chuyên sâu",
                            ViewCount = 580
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
